name: Testing
on: push

jobs: 
  test_project: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Run Tests for Corbetta
      run: 
        pip3 install --user django
        python3 manage.py test