name: Testing
on: push

jobs: 
  test_project: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with: 
        python-version: 3.7
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install --user django
        python manage.py test core