name: Testing
on: push

jobs: 
  test_project: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
    - name: Run tests
      run: |
        pip install django
        pip install django-environ
        cd finance_manager_proj
        python manage.py test core